export default {
  Platform: [{
    title: '平台',
    dataIndex: "name",
    key: 'name',
    align: 'center',
  }, {
    title: '人数',
    dataIndex: "value",
    key: 'value',
    align: 'center',
  }, {
    title: '占比',
    dataIndex: "proportion",
    key: 'proportion',
    align: 'center',
  }],
  Geography: [{
    title: '省份',
    dataIndex: "name",
    key: 'name',
    align: 'center',
  }, {
    title: '活跃人数',
    dataIndex: "value",
    key: 'value',
    align: 'center',
  }, {
    title: '占比',
    dataIndex: "proportion",
    key: 'proportion',
    align: 'center',
  }],
  SDK: [{
    title: 'SDK版本',
    dataIndex: "name",
    key: 'name',
    align: 'center',
  }, {
    title: '人数',
    dataIndex: "value",
    key: 'value',
    align: 'center',
  }, {
    title: '占比',
    dataIndex: "proportion",
    key: 'proportion',
    align: 'center',
  }],
  OS: [{
    title: '操作系统',
    dataIndex: "name",
    key: 'name',
    align: 'center',
  }, {
    title: '人数',
    dataIndex: "value",
    key: 'value',
    align: 'center',
  }, {
    title: '占比',
    dataIndex: "proportion",
    key: 'proportion',
    align: 'center',
  }],
  ISP: [{
    title: '运营商',
    dataIndex: "name",
    key: 'name',
    align: 'center',
  }, {
    title: '人数',
    dataIndex: "value",
    key: 'value',
    align: 'center',
  }, {
    title: '占比',
    dataIndex: "proportion",
    key: 'proportion',
    align: 'center',
  }],
}
